ip: "${HOST_IP}" # curl ifconfig.me
port: 5999
debug: False
worker-ports:
  from: 6000
  to: 7000

 # choose a github repo with bokeh notebooks
remote: "${REPO_LINK}" #Example Repo to use: https://github.com/okoppe/Juypter-Notebook-Repo

 # it will be cloned locally here
local: /tmp/nsdf-data-portal/Juypter-Notebook-Repo
